clus_pT_min:                   15
clus_pT_max:                   30
track_pT_max:                  1.0
jet_pT_min:                    8.0
photon_idvar:                  lambda_0
SIG_DNN_min:                   0.55
SIG_DNN_max:                   0.85
BKG_DNN_min:                   0.0
BKG_DNN_max:                   0.3
SIG_lambda_min:                0.0
SIG_lambda_max:                0.4
BKG_lambda_min:                0.5
BKG_lambda_max:                2.0
SIG_Emax_over_Ecluster_min:    0.0
SIG_Emax_over_Ecluster_max:    0.5
BKG_Emax_over_Ecluster_min:    0.5
BKG_Emax_over_Ecluster_max:    1.0
Eta_max:                       0.5
Cluster_ncell_min:             2
Cluster_locmaxima_max:         2.0
Cluster_distobadchannel:       2.0
EcrossoverE_min:               0.05
iso_max:                       1.0
noniso_min:                    2.0
noniso_max:                    15.0
deta_max:                      0.5
phi_func_bins:                 5
eta_func_bins:                 20
xj_func_bins:                  10
primary_vertex_max:            10
Cluster_isolation_determinant: cluster_iso_its_04
#
pdg_code:                      22
parent_pdg_code:               22
#
Num_events:                    0
